##### BEGIN image/Dockerfile/image-header #####
FROM vcwebio/conteco.rest.base AS base
##### END image/Dockerfile/image-header #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/repo
COPY ./ /conteco/repo/
##### END image/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####
##### END image/Dockerfile/build-instructions #####

##### BEGIN image/Dockerfile/env-labels-footer #####
ENV CONTECO_NAME="kafka_connect" \
    CONTECO_TAG="v1.0.2" \
    CONTECO_BASE="rest.base" \
    CONTECO_BUILD="image"
LABEL io.vcweb.name="kafka_connect" \
      io.vcweb.tag="v1.0.2" \
      io.vcweb.base="rest.base" \
      io.vcweb.build="image" \
      io.vcweb.label="rest.kafka_connect - Conteco" \
      io.vcweb.description="The Conteco REST API client for Confluent Kafka Connect." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.rest.kafka_connect --help" 
##### END image/Dockerfile/env-labels-footer #####
