#!/usr/bin/env bash

export CONTECO_LABEL="rest.kafka_connect - Conteco"
export CONTECO_DESCRIPTION="The Conteco REST API client for Confluent Kafka Connect."

export CONTECO_TYPE="rest"
export CONTECO_NAME="kafka_connect"
export CONTECO_TAG="v1.0.2"
export CONTECO_TAG_TYPE="incremental"

export CONTECO_BASE="rest.base"
export CONTECO_BUILD="image"
